// Indonesian food database with calories per serving
export const indonesianFoods = [
  // Makanan Pokok Golongan A
  { name: "Jagung Rebus", calories: 90, serving: "250g" },
  { name: "Kentang Rebus", calories: 166, serving: "200g" },
  { name: "Ketan Putih", calories: 217, serving: "120g" },
  { name: "Ketupat", calories: 32, serving: "160g" },
  { name: "Lontong", calories: 38, serving: "200g" },
  { name: "Nasi Putih", calories: 175, serving: "100g" },
  { name: "Nasi Putih Kentucky", calories: 349, serving: "225g" },
  { name: "Roti Tawar Serat Tinggi", calories: 149, serving: "60g" },
  { name: "Singkong Rebus", calories: 146, serving: "100g" },
  { name: "Talas Rebus", calories: 98, serving: "100g" },
  { name: "Ubi Rebus", calories: 125, serving: "100g" },

  // Makanan Pokok Golongan B
  { name: "Bubur", calories: 44, serving: "200g" },
  { name: "Crackers", calories: 229, serving: "50g" },
  { name: "Makaroni", calories: 91, serving: "25g" },
  { name: "Mie instant", calories: 168, serving: "50g" },
  { name: "Nasi tim", calories: 88, serving: "100g" },
  { name: "Nasi uduk", calories: 506, serving: "200g" },
  { name: "Roti tawar", calories: 128, serving: "50g" },

  // Makanan Pokok Golongan C
  { name: "Bihun Goreng", calories: 296, serving: "150g" },
  { name: "Bubur Ayam", calories: 165, serving: "200g" },
  { name: "Bubur Sumsum", calories: 178, serving: "100g" },
  { name: "Kentang goreng", calories: 2211, serving: "150g" },
  { name: "Mie goreng", calories: 321, serving: "200g" },
  { name: "Nasi goreng", calories: 267, serving: "100g" },
  { name: "Soun goreng", calories: 263, serving: "100g" },
  { name: "Spaghetti", calories: 642, serving: "300g" },
  { name: "Tape singkong", calories: 260, serving: "150g" },

  // Lauk-Pauk Golongan A
  { name: "Arsik", calories: 94, serving: "95g" },
  { name: "Ayam bakar bumbu kuning", calories: 129, serving: "100g" },
  { name: "Ayam panggang", calories: 164, serving: "100g" },
  { name: "Daging panggang", calories: 150, serving: "70g" },
  { name: "Ikan mas pepes", calories: 143, serving: "200g" },
  { name: "Sambal goreng tempe", calories: 116, serving: "50g" },
  { name: "Telur asin rebus", calories: 138, serving: "75g" },
  { name: "Telur ayam rebus", calories: 97, serving: "60g" },
  { name: "Udang rebus", calories: 91, serving: "100g" },

  // Lauk-Pauk Golongan B
  { name: "Hati ayam goreng", calories: 98, serving: "50g" },
  { name: "Ayam pop", calories: 265, serving: "200g" },
  { name: "Bakso daging sapi", calories: 260, serving: "100g" },
  { name: "Empal daging", calories: 147, serving: "100g" },
  { name: "Ikan bandeng goreng", calories: 180, serving: "100g" },
  { name: "Ikan baronang goreng", calories: 107, serving: "120g" },
  { name: "Ikan bawal goreng", calories: 113, serving: "120g" },
  { name: "Ikan ekor goreng", calories: 107, serving: "100g" },
  { name: "Ikan kembung goreng", calories: 87, serving: "80g" },
  { name: "Ikan lele goreng", calories: 57, serving: "60g" },
  { name: "Ikan patin goreng", calories: 252, serving: "200g" },
  { name: "Ikan selar goreng", calories: 63, serving: "40g" },
  { name: "Ikan tenggiri goreng", calories: 85, serving: "60g" },
  { name: "Ikan teri goreng", calories: 66, serving: "50g" },
  { name: "Ikan tuna goreng", calories: 110, serving: "60g" },
  { name: "Kerang rebus", calories: 59, serving: "100g" },
  { name: "Makaroni skotel", calories: 177, serving: "50g" },
  { name: "Tahu bacem", calories: 147, serving: "100g" },
  { name: "Tempe bacem", calories: 157, serving: "50g" },
  { name: "Telur mata sapi", calories: 40, serving: "60g" },
  { name: "Tempe goreng", calories: 118, serving: "50g" },
  { name: "Tenggiri bumbu kuning", calories: 94, serving: "90g" },
  { name: "Udang goreng besar", calories: 68, serving: "80g" },

  // Lauk-Pauk Golongan C
  { name: "Abon sapi", calories: 158, serving: "50g" },
  { name: "Ayam goreng kecap", calories: 358, serving: "75g" },
  { name: "Ayam panggang", calories: 358, serving: "80g" },
  { name: "Sayap ayam", calories: 63, serving: "50g" },
  { name: "Daging balado", calories: 147, serving: "50g" },
  { name: "Dendeng balado", calories: 338, serving: "40g" },
  { name: "Gulai ayam", calories: 165, serving: "100g" },
  { name: "Gulai cumi", calories: 183, serving: "100g" },
  { name: "Gulai kepala ikan kakap", calories: 218, serving: "320g" },
  { name: "Gulai limpa", calories: 294, serving: "60g" },
  { name: "Gulai tunjang", calories: 251, serving: "80g" },
  { name: "Ikan kembung balado", calories: 236, serving: "125g" },
  { name: "Ikan teri", calories: 213, serving: "50g" },
  { name: "Kakap goreng tepung", calories: 119, serving: "80g" },
  { name: "Kakap panir", calories: 220, serving: "75g" },
  { name: "Keripik tante", calories: 68, serving: "25g" },
  { name: "Meet ball / daging cincang", calories: 168, serving: "50g" },
  { name: "Ayam Kentucky paha atas", calories: 194, serving: "150g" },
  { name: "Perkedel jagung", calories: 108, serving: "50g" },
  { name: "Perkedel kentang", calories: 123, serving: "50g" },
  { name: "Pu yung hai", calories: 114, serving: "50g" },
  { name: "Rendang daging", calories: 285, serving: "75g" },
  { name: "Sate ayam", calories: 466, serving: "100g" },
  { name: "Ayam kentucky sayap", calories: 116, serving: "150g" },
  { name: "Semur ayam", calories: 177, serving: "50g" },
  { name: "Sambal goreng hati + kentang", calories: 127, serving: "100g" },
  { name: "Sambal goreng tempe teri", calories: 276, serving: "150g" },
  { name: "Sambal goreng hati sapi", calories: 200, serving: "100g" },
  { name: "Sambal goreng udang + kentang", calories: 123, serving: "100g" },
  { name: "Sop sapi", calories: 227, serving: "260g" },
  { name: "Tahu goreng", calories: 111, serving: "100g" },
  { name: "Tahu isi", calories: 124, serving: "150g" },
  { name: "Tahu sumedang", calories: 113, serving: "100g" },
  { name: "Telur dadar", calories: 188, serving: "75g" },

  // Sayuran Golongan A
  { name: "Acar kuning", calories: 53, serving: "75g" },
  { name: "Bening ayam", calories: 18, serving: "50g" },
  { name: "Cah labu siam", calories: 41, serving: "100g" },
  { name: "Sayur asam", calories: 88, serving: "100g" },
  { name: "Sop ayam kombinasi", calories: 95, serving: "100g" },
  { name: "Sop bayam", calories: 78, serving: "50g" },
  { name: "Sop kimlo", calories: 104, serving: "100g" },
  { name: "Sop mutiara jagung", calories: 113, serving: "100g" },
  { name: "Sop oyong misoa", calories: 106, serving: "100g" },
  { name: "Sop telur puyuh", calories: 116, serving: "100g" },

  // Sayuran Golongan B
  { name: "Sayur lodeh", calories: 61, serving: "100g" },
  { name: "Cah jagung putren", calories: 59, serving: "100g" },
  { name: "Cah kacang panjang", calories: 72, serving: "100g" },
  { name: "Sop oyong telur puyuh", calories: 134, serving: "100g" },
  { name: "Setup kentang buncis", calories: 95, serving: "100g" },
  { name: "Tumis buncis", calories: 52, serving: "100g" },
  { name: "Tumis daun singkong", calories: 151, serving: "120g" },
  { name: "Tumis kacang panjang+jagung", calories: 118, serving: "125g" },

  // Sayuran Golongan C
  { name: "Buntil", calories: 106, serving: "100g" },
  { name: "Gudeg", calories: 132, serving: "150g" },

  // Minuman Golongan A
  { name: "Teh", calories: 0.4, serving: "1 cangkir" },
  { name: "Kopi", calories: 18, serving: "1 cangkir" },
  { name: "Jus tomat", calories: 20, serving: "100g" },
  { name: "Jus melon", calories: 35, serving: "150g" },
  { name: "Es kelapa muda", calories: 42, serving: "100g" },

  // Minuman Golongan B
  { name: "Es cendol", calories: 168, serving: "100g" },
  { name: "Susu skim", calories: 54, serving: "15g" },

  // Makanan Siap Saji A
  { name: "Asinan", calories: 208, serving: "250g" },
  { name: "Tauge goreng", calories: 243, serving: "250g" },

  // Makanan Siap Saji B
  { name: "Gado-gado", calories: 295, serving: "150g" },
  { name: "Ketoprak", calories: 153, serving: "250g" },
  { name: "Pempek", calories: 384, serving: "200g" },
  { name: "Rawon", calories: 331, serving: "160g" },
  { name: "Soto ayam", calories: 101, serving: "100g" },
  { name: "Soto padang", calories: 127, serving: "100g" },
  { name: "Tongseng", calories: 331, serving: "120g" },

  // Makanan Siap Saji C
  { name: "Hamburger", calories: 257, serving: "125g" },
  { name: "Kerupuk Palembang", calories: 168, serving: "50g" },
  { name: "Kerupuk udang", calories: 72, serving: "20g" },
  { name: "Mie bakso", calories: 302, serving: "200g" },
  { name: "Nasi tim ayam", calories: 588, serving: "420g" },
  { name: "Pizza", calories: 163, serving: "125g" },
  { name: "Sate kambing", calories: 729, serving: "180g" },
  { name: "Sayur krecek", calories: 249, serving: "175g" },
  { name: "Siomay", calories: 361, serving: "100g" },
  { name: "Soto betawi", calories: 135, serving: "150g" },
  { name: "Soto Makassar", calories: 525, serving: "150g" },
  { name: "Soto sulung", calories: 86, serving: "150g" },

  // Buah Golongan A
  { name: "Apel", calories: 92, serving: "160g" },
  { name: "Apel merah", calories: 82, serving: "140g" },
  { name: "Belimbing", calories: 80, serving: "160g" },
  { name: "Duku", calories: 81, serving: "200g" },
  { name: "Jambu air", calories: 35, serving: "60g" },
  { name: "Jambu biji", calories: 157, serving: "320g" },
  { name: "Jeruk medan", calories: 46, serving: "140g" },
  { name: "Jeruk Pontianak", calories: 67, serving: "150g" },
  { name: "Jeruk Sunkist", calories: 40, serving: "200g" },
  { name: "Mangga manalagi", calories: 72, serving: "100g" },
  { name: "Nanas", calories: 104, serving: "200g" },
  { name: "Papaya", calories: 46, serving: "100g" },
  { name: "Pir", calories: 80, serving: "200g" },
  { name: "Pisang rebus", calories: 136, serving: "125g" },
  { name: "Salak", calories: 63, serving: "150g" },
  { name: "Semangka", calories: 48, serving: "150g" },

  // Buah Golongan B
  { name: "Alpokat", calories: 85, serving: "100g" },
  { name: "Anggur", calories: 60, serving: "125g" },
  { name: "Lengkeng", calories: 79, serving: "100g" },
  { name: "Melon", calories: 46, serving: "120g" },
  { name: "Mangga harum manis", calories: 90, serving: "300g" },
  { name: "Pir hijau", calories: 105, serving: "200g" },
  { name: "Pisang ambon", calories: 74, serving: "100g" },
  { name: "Pisang barangan", calories: 236, serving: "200g" },
  { name: "Pisang mas", calories: 120, serving: "125g" },
  { name: "Pisang raja", calories: 126, serving: "150g" },
  { name: "Sirsak", calories: 55, serving: "125g" },

  // Buah Golongan C
  { name: "Durian", calories: 134, serving: "100g" },
  { name: "Rambutan", calories: 69, serving: "100g" },
  { name: "Sawo", calories: 92, serving: "100g" },

  // Makanan Ringan Golongan A
  { name: "Arem-arem", calories: 225, serving: "75g" },
  { name: "Bubur kacang hijau", calories: 102, serving: "100g" },
  { name: "Ketupat ketan", calories: 216, serving: "120g" },
  { name: "Lemper", calories: 247, serving: "70g" },
  { name: "Lepet", calories: 210, serving: "120g" },
  { name: "Lepet ketan", calories: 346, serving: "170g" },

  // Makanan Ringan Golongan B
  { name: "Bolu gulung", calories: 300, serving: "110g" },
  { name: "Cakwee", calories: 143, serving: "50g" },
  { name: "Getuk lindri", calories: 127, serving: "60g" },
  { name: "Hot dog", calories: 285, serving: "100g" },
  { name: "Kerak telur", calories: 599, serving: "120g" },
  { name: "Kue nagasari", calories: 149, serving: "70g" },
  { name: "Kue pancong", calories: 231, serving: "80g" },
  { name: "Mini croissant", calories: 406, serving: "80g" },
  { name: "Sandwich", calories: 164, serving: "100g" },
  { name: "Serabi pandan", calories: 137, serving: "60g" },
  { name: "Semar mendem", calories: 247, serving: "100g" },
  { name: "Uli + tape ketan", calories: 559, serving: "160g" },

  // Makanan Ringan Golongan C
  { name: "Bakpia", calories: 68, serving: "25g" },
  { name: "Bakwan", calories: 270, serving: "100g" },
  { name: "Bika ambon", calories: 99, serving: "50g" },
  { name: "Black forest", calories: 585, serving: "200g" },
  { name: "Cara bikang", calories: 128, serving: "70g" },
  { name: "Cheese cake", calories: 281, serving: "10g" },
  { name: "Dunkin donat keju", calories: 283, serving: "170g" },
  { name: "Emping melinjo asin", calories: 173, serving: "25g" },
  { name: "Kastengels", calories: 426, serving: "100g" },
  { name: "Keju lembaran", calories: 65, serving: "20g" },
  { name: "Kerupuk mie", calories: 119, serving: "25g" },
  { name: "Klepon", calories: 68, serving: "60g" },
  { name: "Kroket kentang", calories: 146, serving: "75g" },
  { name: "Kue apem", calories: 151, serving: "60g" },
  { name: "Kue cubit", calories: 183, serving: "60g" },
  { name: "Kue cucur", calories: 152, serving: "90g" },
  { name: "Kue lumpur", calories: 232, serving: "80g" },
  { name: "Kue pukis", calories: 181, serving: "40g" },
  { name: "Lapis legit", calories: 307, serving: "50g" },
  { name: "Lemet", calories: 603, serving: "120g" },
  { name: "Lopis ketan", calories: 350, serving: "125g" },
  { name: "Lumpia", calories: 76, serving: "60g" },
  { name: "Martabak keju", calories: 265, serving: "100g" },
  { name: "Martabak mesir", calories: 200, serving: "100g" },
  { name: "Martabak telur", calories: 196, serving: "95g" },
  { name: "Muffin coklat", calories: 361, serving: "80g" },
  { name: "Muffin keju", calories: 400, serving: "80g" },
  { name: "Nastar", calories: 538, serving: "150g" },
  { name: "Onde-onde", calories: 317, serving: "65g" },
  { name: "Pastel", calories: 302, serving: "75g" },
  { name: "Potato chips", calories: 298, serving: "170g" },
  { name: "Putu mayang", calories: 98, serving: "120g" },
  { name: "Peyek kacang", calories: 250, serving: "50g" },
  { name: "Risol", calories: 247, serving: "100g" },
  { name: "Roti coklat", calories: 240, serving: "100g" },
  { name: "Sosis solo", calories: 191, serving: "50g" },
  { name: "Sus vla", calories: 129, serving: "85g" },
  { name: "Talam hijau", calories: 292, serving: "70g" },
]

